# Generated by Django 4.1.4 on 2023-01-20 20:16

import clinica.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=11)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('crm', models.CharField(max_length=7)),
                ('email', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=11)),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.especialidade')),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.CharField(choices=[('8 as 10h', '8:00 as 10:00'), ('10 as 12h', '10:00 as 12:00'), ('14 as 17h', '14:00 as 17:00'), ('17 as 19h', '17:00 as 19:00')], default='1', max_length=20)),
                ('data', models.DateField(help_text='Insira a data desejada.', validators=[clinica.models.validar_dia])),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.medico')),
            ],
            options={
                'unique_together': {('data', 'hora')},
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda_medico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinica.agenda')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.cliente')),
            ],
            options={
                'unique_together': {('cliente', 'agenda_medico')},
            },
        ),
    ]
